version: '3.7'

services:
  app:
    build: .
    depends_on:
      - postgres
      - proxy
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.entryPoints=web
      - traefik.http.routers.app.middlewares=secureRedirect@file
      - traefik.http.routers.app.rule=Host(`flicklist.localhost`)
      - traefik.http.routers.app-secured.entryPoints=web-secure
      - traefik.http.routers.app-secured.rule=Host(`flicklist.localhost`)
      - traefik.http.routers.app-secured.tls=true
    stdin_open: true
    tty: true
    volumes:
      - .:/srv/app
      - ./public:/srv/app/public
      - type: tmpfs
        target: /srv/app/tmp/pids/

  cable:
    command: puma -p 28080 cable/config.ru
    depends_on:
      - redis
    image: flick_list_app:latest
    ports:
      - 28080:28080
    volumes:
      - .:/srv/app

  sidekiq:
    command: sidekiq -C config/sidekiq.yml.erb
    depends_on:
      - postgres
      - redis
    image: flick_list_app:latest
    volumes:
      - .:/srv/app

  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./tmp/data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:6.0-alpine
    restart: always
    volumes:
      - ./tmp/data/redis:/data

  proxy:
    image: traefik:v2.2
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/proxy/traefik.yml:/etc/traefik/traefik.yml
      - ./docker/proxy/dynamic_config.yml:/etc/traefik/dynamic_config.yml
      - ./docker/proxy/certs/server.crt:/etc/ssl/server.crt
      - ./docker/proxy/certs/server.key:/etc/ssl/server.key
